MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
RGBLIGHT_ENABLE = yes
ENCODER_ENABLE = yes
LTO_ENABLE = yes
OLED_ENABLE = yes

CONVERT_TO=rp2040_ce

VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes